language: en
pipeline:
- name: SpacyNLP
  model: en_core_web_md
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: LexicalSyntacticFeaturizer
- name: DIETClassifier
  epochs: 50
  constrain_similarities: true
- name: EntitySynonymMapper
policies:
- name: TEDPolicy
  batch_size: 100
  epochs: 5
  validation_split: 0.2
- name: MemoizationPolicy
- name: RulePolicy
